In [1]:
# for i in range(0,10):
#     for j in range(0,i):
#         print("* ",end="")
#     print()

# str = "Barnava"
# print(str[:2:-1])

# tup = (0,1,35,56,1)

# print(type(tup) , tup[::-1])

# list = []

# for i in range(3):
#     list.append(input(f"Enter the name at {i}: "))
# print(f"your favourite movies are {list[:]}")

# list =[]
# list_range = int(input("Enter the range: "))
# for i in range(list_range):
#     list.append(input(f"Enter the element at {i}: "))
# list2 = list[::-1]

# if(list == list2):
#     print("palindrome")
# else:
#     print("not palindrome")

# touple = ()
# n = int(input("Enter the number of elements you want to add in the touple: "))
# for i in range(n):
#     touple+=input(f"Enter the element at {i}: ")
# print(touple)


# try:
#     f = open("text.txt")
#     num = int(f.read())
#     print(100/num)
# except ValueError:
#     print("Value Error Occurred")
# except ZeroDivisionError:
#     print("Zero Division Error Occurred")
# finally:
#     try:
#         f.close()
#         print("File Closed")
#     except:
#         print("File was not opened")

# str = input("Enter your string")

# for chars in str :
#     print(chars)

# str = input("Enter your string: ")
# for chars in str:
#     count =0
#     for chs in str:
#         if(chars == chs):
#             count+=1
#     print(f"{chars} count = {count}")

# str = input("Enter your string:")
# str = str[:2]+'J'+str[2:]
# print(str)

# list = ["apple","banana","cherry","kiwi","mango"]
# list_str = '-<>-'.join(list)
# pos = list_str.find(',')
# tup = list_str.split('-<>-')

# print(pos)
# print(tup,type(tup))

# def age(str):
#     name,dob,dod = str.split('*')
#     yob = int(dob.split('-')[2])
#     yod = int(dod.split('-')[2])
#     return yod - yob
# str = input("Enter the input in the format <Name*Date of birth*Date of death>\nYour statement: ")
# name = str.split('*')[0]
# print(f"{name} lived about {age(str)} years.")

# str = input("Enter the string: ")
# sub_string = input("Enter the sub-string your want to find: ")

# if sub_string in str:
#     print(f"'{sub_string}' is present in '{str}'")
# else:
#     print(f"'{sub_string}' is not present in '{str}'")

# str = "Hello World.mp3"
# s = [".mp3",".wav",".flac"]
# val = str.endswith(tuple(s),0,len(str))
# print(val)

# str = """Hello! 
# Hello World!!
# My name is Barnava\tKumar\tChakraborty"""
# lines = str.splitlines()
# print(f"{lines}\n{type(lines)}")

# str = "Hello World.mp3"
# s = [".mp3",".wav",".flac"]
# val = str.startswith(tuple(s),0,len(str))
# print(val,type(val))

# dictionary = {
#     "name":"Barnava",
#     "age":20,
#     "courses":["BBA","MBA","BCA"],
#     "isEmployed":False
# }

# print(dictionary)

# class Students:
#     def __init__(self,name,age,course,pwd):
#         self.name = name
#         self.age = age
#         self.course = course
#         self.__pwd = pwd
#     def changePwd(self,old,new):
#         if(old == self.__pwd):
#             self.__pwd = new
#             print("Password Changed Successfully")
#         else:
#             print("Old Password didn't match")
# name = input("Enter your name: ")
# age = int(input("Enter your age: "))
# course = input("Enter your course: ")
# pwd = input("Set your password: ")

# s1 = Students(name, age, course, pwd)

# old = input("Enter your old password: ")
# new = input("Enter your new password: ")
# s1.changePwd(old,new)

# class Student:
#     def __init__(self,phy,chem,math):
#         self.phy = phy
#         self.chem = chem
#         self.math = math
    
#     @property
#     def percentage(self):
#         return str((self.phy+self.chem+self.math)/300) + "%"

# s1 = Student(45,56,76)
# print(s1.percentage)
# s1.math = 98
# print(s1.percentage)

# import numpy as NP

# a = NP.array([[1,2,3,4,]],dtype = "int64")
# b = [1,2,3,4]
# print(b)
# print(a)
# b = NP.array(b)
# print(b)

# c = a*b
# print(c)
# print(str(c.shape)[1],a.dtype)

# arr = NP.repeat(a,3,axis = 1)
# print(arr)

# a = NP.ones((5,5))
# b = NP.zeros((3,3))
# b[1,1] = 9
# a[1:-1,1:-1] = b
# print(a)
# import math 
# import matplotlib.pyplot as plt
# import numpy as np

# x = np.arange(0,math.pi*2,0.1)
# y = np.sin(x)
# plt.plot(x,y,'g')
# plt.xlabel('angle')
# plt.ylabel('sine function')
# plt.title('sine function')
# plt.show()

# import math
# import numpy as np
# from matplotlib import pyplot as plt

# fig,a = plt.subplots(2,2)

# x = np.arange(0,50,5)
# a[0][0].plot(x,x*x)

# a[1][1].plot(x,x*x*x)

# plt.show()

# import numpy as np

# A = ["hello","world","!!!","\n","Welcome","to","python","."]
# print(np.random.permutation(A))

# import numpy as np

# a = np.random.rand(1000)

# import matplotlib.pyplot as plt

# plt.hist(a,bins = 100,color="red")
# plt.show()

# import numpy as np

# a = np.random.rand(2,3)
# b = np.random.randint(2,3)

# print(f"a: {a}\ttype: {type(a)}\nb: {b}\ttype:{type(b)}\n\n")

# c = np.arange(100)
# d = c.reshape(4,5,5)
# print(d,"\t",d.shape)



Numpy.hstack


Numpy.vstack


Numpy.sort


In [2]:
import numpy as np
low,high = map(int,(input(f"Enter {name}'s value: ") for name in ("low","high")))
A = np.round(10*np.random.rand(2,3))+(np.random.randint(low,high+1,size = 6).reshape(2,3))
while True:
    low2,high2 = map(int,(input(f"Enter {name}'s value: ") for name in ("low","high")))
    if (low2,high2) != (low,high):
        break
    print("Enter another range...")
    
B = np.round(10*np.random.rand(2,3))+(np.random.randint(low2,high2+1,size = 6).reshape(2,3))

print(A,"\n\n",B)

[[101.  82.  67.]
 [ 67. 100.  99.]] 

 [[ 75.  94.  77.]
 [ 69. 108.  88.]]


In [3]:
print(A)

[[101.  82.  67.]
 [ 67. 100.  99.]]


In [4]:
C = np.hstack((A,B))
print(C)
print()
print()
D = np.vstack((A,B))
print(D)



[[101.  82.  67.  75.  94.  77.]
 [ 67. 100.  99.  69. 108.  88.]]


[[101.  82.  67.]
 [ 67. 100.  99.]
 [ 75.  94.  77.]
 [ 69. 108.  88.]]


In [5]:
E = np.random.permutation(np.round(np.linspace(20,50,10)))
print(E)
E = np.sort(E)
print(E)

[50. 27. 30. 20. 33. 40. 23. 43. 47. 37.]
[20. 23. 27. 30. 33. 37. 40. 43. 47. 50.]


In [6]:
a = (np.round((np.linspace(20,50,20))).astype(int)).reshape(5,4)
print(a)
b = np.sort(a.flatten()).reshape(a.shape,order = 'F')
print(b)

[[20 22 23 25]
 [26 28 29 31]
 [33 34 36 37]
 [39 41 42 44]
 [45 47 48 50]]
[[20 28 36 44]
 [22 29 37 45]
 [23 31 39 47]
 [25 33 41 48]
 [26 34 42 50]]


%timeit


In [7]:
def sum_arr(G):
    Sum = 0
    for x in G:
        Sum+=x 
    return Sum
Q = np.random.rand(10000000)
%timeit sum(Q)
%timeit np.sum(Q)
%timeit sum_arr(Q)

890 ms ± 279 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
21.4 ms ± 7.44 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
820 ms ± 144 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


PANDAS


In [9]:
import pandas as pd
import string
def random_alpha_indexed_numbers(n):
    num = pd.Series(np.round(np.linspace(23,67,n)).astype(int),index = list(string.ascii_lowercase[:n]))
    return num
n = int(input("Enter the number of numbers you want"))
nums = random_alpha_indexed_numbers(n)
print(f"indices: numbers")
string_format = "  "+nums.index + "    : " + nums.astype(str)
type_num = str(type(nums)).split("'")[1]
print("\n".join(string_format),"\ntype: ",type_num)

indices: numbers
  a    : 23
  b    : 67 
type:  pandas.core.series.Series


In [ ]:
gpa = {
    'A': 4,
    'B': 3.5,
    'C': 3,
    'D': 2.5
}

marks = {
    'E': '90%',
    'F': '85%',
    'G': '80%',
    'H': '75%'
}

data = pd.DataFrame({
    'gpa': gpa,
    'marks': marks
})



print(data)

Tkinter


In [1]:
from tkinter import *

root = Tk()
loc = [1]
def display():
    myLabel = Label(root,text="Hello World", padx= 5, pady = 5)
    myLabel.grid(row = loc[0],column= loc[0])
    loc[0]+=1

style = {
    "state" : "active",
    "padx" : 5,
    "pady" : 4,
    "fg":"white",
    "bg" : "black",
    "font" :("Monospace",20)
}
e = Entry(root,
          borderwidth= 10,
          width=100,
          font =("Monospace",20))
e.grid(
    row=0,
    column=0,
    pady = 4
)
myButton = Button(root,
                  text = "Click Me!",
                  **style,
                  command=display)
myButton.grid(column=1,row=0)


                
root.mainloop()

In [1]:
from tkinter import *

root = Tk()

Expression = Entry(
    root,
    font=("Monospace", 20),
    justify="left",
)
Expression.insert(0, '0')
Expression.grid(row=0, column=0, columnspan=5, sticky="we", pady=10)

def click(val):
    current = Expression.get()
    if current == "0":
        Expression.delete(0, END)
        Expression.insert(0, val)
    else:
        Expression.insert(END, val)

def equal():
    try:
        exp = Expression.get()
        exp = exp.replace("x","*")
        Expression.delete(0,END)
        Expression.insert(0,eval(exp))
    except:
        Expression.delete(0,END)
        Expression.insert(0,"Error")

layout = [
    ['7','8','9','Del','AC'],
    ['4','5','6','x','/'],
    ['1','2','3','+','-']
]

for r, row in enumerate(layout):
    for c, char in enumerate(row):
        if char == 'Del':
            cmd = lambda: Expression.delete(len(Expression.get())-1,END) if Expression.get() != 'Error' else Expression.delete(0,END)
        elif char == 'AC':
            cmd = lambda: Expression.delete(0,END)
        else: cmd = lambda ch = char: click(ch)
        btn = Button(
            root,
            text=char,
            padx = 20,
            pady = 20,
            command=cmd
        )
        btn.grid(row = r+1,column = c,sticky = "we")    

zero_btn = Button(
    root,
    text = '0',
    padx = 20,
    pady = 20,
    command= lambda:click('0')
)
zero_btn.grid(row = 4,column=0,sticky="we",columnspan=2)

equal_btn = Button(
    root,
    text = '=',
    padx = 20,
    pady = 20,
    command= equal
)
equal_btn.grid(row = 4,column=2,sticky="we",columnspan=2)
root.iconbitmap('E:/python/tkinter/Frame 1.ico')

root.mainloop()

In [1]:
from tkinter import *
from PIL import  ImageTk,Image

root = Tk()
root.title('Image')
my_image = ImageTk.PhotoImage(Image.open("E:/python/tkinter/Frame 1.png"))
mylabel = Label(image=my_image)
mylabel.pack()
root.mainloop()

In [6]:
from tkinter import *

root = Tk()

frame = LabelFrame(root,text="Frame",padx=10,pady=10)
frame.pack(padx=10,pady=10)

b = Button(frame,text="Click Here!!")
b.pack()

root.mainloop()

In [9]:
from tkinter import messagebox
root = Tk()
def popup():
    messagebox.showinfo("This is my popup","Hello World")

Button(root,text = "Popup",command = popup).pack()
root.mainloop()

In [15]:
root =Tk()
response = 'no'
def openNewWindow():
    global response; response = messagebox.askyesno("Response","Want to open new Window")
    if response == True:
        top = Toplevel(root)
        Label(top,text="Hello World!!").pack()
        Button(top,text = "Exit",command = top.destroy).pack()

Button(root,text = "show new window ", command = openNewWindow).pack()
root.mainloop()

In [27]:
from tkinter import *

root = Tk()

ribbon = Frame(root,relief=SOLID)
ribbon.pack(side='top', fill='x')

file = Button(ribbon, text="File", relief=FLAT)
file.pack(side='left', padx=5, pady=2)   
border = Frame(root, height=1, bg="grey")
border.pack(fill='x')
root.mainloop()

In [ ]:
from tkinter import filedialog
from PIL import Image,ImageTk
root = Tk()
def openFile():
    global my_image
    root.filename = filedialog.askopenfilename(
        initialdir="E:/python",
        title="Select a file",
        filetypes=(
            ("png files","*.jpg"),
            ("ico files","*.ico"),
            ("Python files","*.py")
            ("All files","*.*")
        )
    )
    my_image = ImageTk.PhotoImage(Image.open(root.filename))
    Label(image = my_image).pack()
    imagenm = root.filename[root.filename.rfind('/')+1:]
    label = Label(root,text = imagenm)
    label.pack()


Button(text= "Open",command = openFile).pack() 
root.mainloop()


In [38]:
root = Tk()
clicked = StringVar()
clicked.set("Monday")
drop = OptionMenu(
    root,
    clicked,
    "Monday",
    "Tuesdsy",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday"
)
drop.pack()
root.mainloop()

In [40]:
from tkinter import *
import sqlite3 

root = Tk()
root.title('Database')
root.geometry("400x400")

#Databases

#Creating a database or connecting to one 
conn = sqlite3.connect('address_databook.db')

#Creating cursor
c = conn.cursor()

#Createing Table 
c.execute("""CREATE TABLE addresses(
          firstname text,
          lastname text,
          addresses text,
          city text,
          state text,
          zipcode integer
          )""")

#Commit Changes
conn.commit()

#Close Connection
conn.close()

root.mainloop()


In [3]:
from tkinter import *

root = Tk()

entrystyle = {
    "relief": "solid",
    "font": ("Lucida Console",10),
    "fg" : "black",
    "bg" : "white",
    "bd" : 1,
    "width" : 40,
}

entry = Entry(
    root,
    **entrystyle,
)
llist = []
def put_entry_in_var():
    entry.pack(expand = True)
    llist.append(entry.get())


root.mainloop()

print("\n".join(llist))

In [4]:
class Item:
    def claculate_total_price(self, x,y ):
        return x*y

item1 = Item()
item1.name = "Phone"
item1.price = 100
item1.quantity = 5

print(item1.claculate_total_price(item1.price,item1.quantity))
print(item1)


500


In [ ]:
import csv

class Item:
    
    rate = 0.8
    all = []
    def __init__(self, name:str, price:float, quantity = 0):
        
        assert price >= 0 , f"Price : {price} is not an acceptable price"
        assert quantity >= 0 , f"Quantity : {quantity} is not an acceptable price"        
        
        self.name = name
        self.price = price
        self.quantity = quantity
        
        Item.all.append(self)
    
    def apply_offer(self):
        self.price = self.price*Item.rate
    
    def total_cost(self):
        return self.quantity*self.price
    
    def print_attr(self):
        print(
            f"obg:{self.__dict__}\n"
            f"cls:\n"+
            "\n".join(f"{key}:{val}" for key,val in Item.__dict__.items()) 
        )
    @classmethod
    def instantiate_objs(cls):
        with open("Items.csv","r") as f:
            data = csv.DictReader(f)
            data_list = list(data)
        for items in data_list:
            Item(
                name = items["name"],
                price = float(items["price"]),
                quantity = int(items["quantity"])
            )
    def __repr__(self):
        return f"Item('{self.name}',{self.price},{self.quantity})"
   
Item.instantiate_objs() 
print(Item.all)
# item1 = Item("Laptop", 1000, 2)
# item1.apply_offer()
# print(f"product:{item1.name}\t"
#       f"price: {item1.price}\t"
#       f"quantity: {item1.quantity}\t"
# )
# item2 = Item("Microwave", 3000, 1)
# item3 = Item("Fan", 500, 8)
# item4 = Item("Fridge", 10000, 10)
# item5 = Item("Phone", 100000, 4)

# print("\n".join(str(items) for items in Item.all))    

[Item('Laptop',10000.0,2), Item('Car',67000.0,3), Item('Book',200.0,7), Item('Bluetooth Speaker',5000.0,1)]


In [31]:
class Phone(Item):
    def __init__(self,name:str, price:float, quantity = 0,broken_phone = 0):
        super().__init__(name,price,quantity)
        self.broken_phone = broken_phone
    def __repr__(self):
        base = super().__repr__()
        return f"Phone{base[base.find('('):-1]},{self.broken_phone})"
phone1 = Phone("Iphone",20000,2,1)
repr_phone1 = repr(phone1)
phone2 =eval(repr_phone1)
print(phone2)
print(phone1)

Phone('Iphone',20000,2,1)
Phone('Iphone',20000,2,1)
